<a href="https://colab.research.google.com/github/heewoonjeong/AI8_Study/blob/main/%EC%98%81%ED%99%94_%EB%A6%AC%EB%B7%B0(%EC%9E%84%EB%B2%A0%EB%94%A9).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##  단어 임베딩
원-핫 인코딩으로 벡터의 길이가 길어진다는 단점이 있음 이러한 공간적 낭비를 위해 등장한 것이 **단어 임베딩**(word.embedding) 주어진 배열을 정해진 길이로 압출 

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.text import text_to_word_sequence
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Embedding, Dense, Flatten
from tensorflow.keras.models import Sequential

from numpy import array 

In [ ]:
# embedding() 함수는 입력과 출력의 크기를 나타내는 두개의 매개변수가 있어야합니다 
# embedding(16,4 , inpt_length=2 입력이 2개씩 )
# 입력될 총단어수 16 임베딩후 출력되는 벡터크기는 4 
# embedding() (입력,출력,출력몇개) 3가지의 파라미터로 구성 
model = Sequential() 
model.add(Embedding(16,4))

In [ ]:
# 영화 리뷰 립러닝 모델학습 긍정1 부정2
docs = [ '너무 재밌네요 ','최고예요','참 잘 만든 영화예요', '추천하고 싶은 영화 입니다 ','한 번 더 보고싶네요', '글쎄요','별로예요','생각보다 지루하네요','연기가 어색해요','재미없어요']


In [ ]:
classes = array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
# 토큰화 Tokenizer()함수의 fit_on_texts 단어의 하나의 토큰으로 변환 
# 토큰화된 결과를 출력해 확인 합니다 
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index) 

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화': 10, '입니다': 11, '한': 12, '번': 13, '더': 14, '보고싶네요': 15, '글쎄요': 16, '별로예요': 17, '생각보다': 18, '지루하네요': 19, '연기가': 20, '어색해요': 21, '재미없어요': 22}


In [ ]:
# 지정된 인덱스로 저장 
x= token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n" , x)


리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15], [16], [17], [18, 19], [20, 21], [22]]


In [ ]:
# 최고예요는 3하나로 가능한데 참 잘 만든 영화에요는 4,5,6,7 이 들어감으로 길이 마추기 
# 서로 다른길이의 데이터를 4로 마추기 
padded_x = pad_sequences(x ,4) 
print("\n패딩 결과 :\n", padded_x)
print(word_size)


패딩 결과 :
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  0  0 16]
 [ 0  0  0 17]
 [ 0  0 18 19]
 [ 0  0 20 21]
 [ 0  0  0 22]]
23


In [ ]:
# 총몇개의 인덱스가 입력되어야하는지 정하고 word_size 라는 변수를 만든후 길이를 세는 
# len()함수 이용 word_index 값을 앞서만든 변수에 대입 이때 단어맨 앞에 0이 먼저 나와야함으로 +1을 해줌 
word_size = len(token.word_index) +1 

In [ ]:
# 출력 장치 만들차례 word_size만큼 입력 값을 이용해 여덟개의 임베딩 결과를 만들겠습니다.
# 여기서 8라이는 숫자는 임의로 정한것 이고 데이터 에 따라 적절한 값으로 바꿀수 있습니다 
# 이때 만들어진 여덟개의 임베딩 결과는 우리 눈에 보이지 않습니다.
# 끝으로 매번 입력될 '단어수'를 정합니다 패딩과정에 거쳐 4개로 길이를 맞추어 주었으므로 네개의 단어가 들어가게하면 임베딩과정 은 다음한줄로 표현됩니다 
# Embedding(word_size, 8, input_length =4)
# 모델을 만들어봅시다 
model = Sequential()
model.add(Embedding(word_size, 8, input_length =4))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.summary()
# 최적화 함수 adam을 사용하고 오차함수로는 binara_categorical을 사용했습니다 
# 그리고 20번 반복하고나서 정확도를 계산해 출력하게 했습니다. 
model.compile(optimizer='adam', loss='binary_crossentropy',metrics= ['accuracy'])
model.fit(padded_x, classes, epochs=20)
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 4, 8)              184       
                                                                 
 flatten_4 (Flatten)         (None, 32)                0         
                                                                 
 dense_4 (Dense)             (None, 1)                 33        
                                                                 
Total params: 217
Trainable params: 217
Non-trainable params: 0
_________________________________________________________________
Epoch 1/20
1/1 [==============================] - 0s 500ms/step - loss: 0.6934 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6914 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6895 - accuracy: 0.6000
Epoch 4/20
1/1 [==============